pagopa/cstar-platform-azure-devops

- azure-devops/idpay-projects/06_pipeline_idpay-onboarding-workflow.tf
enable code review pipeline
need to execute code review on PR for the related project
---
> enable code review pipeline

- azure-devops/idpay-projects/00_locals.tf
add value for initiative backend endpoint
integration with BE
---
> IPE-174 - update url_api_initiative

- azure-devops/iac-projects/04_backups.tf
> Apim backup only in business hours

- azure-devops/iac-projects/03_iac_core.tf
- azure-devops/iac-projects/03_iac_idpay.tf
- azure-devops/iac-projects/04_backups.tf
- azure-devops/iac-projects/README.md
> fix: Idpay code review pipeline

- azure-devops/idpay-projects/99_locals.tf
Add new env variables for token validate and generation endpoint
New endpoint for token exchange security policy
---
> IPE-240 add endpoint for BE pre login

- azure-devops/idpay-projects/06_pipeline_idpay-admissibility-assessor.tf
- azure-devops/idpay-projects/06_pipeline_idpay-group.tf
- azure-devops/idpay-projects/06_pipeline_idpay-iban.tf
- azure-devops/idpay-projects/06_pipeline_idpay-idpay-portal-welfare-backend-config.tf
- azure-devops/idpay-projects/06_pipeline_idpay-idpay-portal-welfare-backend-initiative.tf
- azure-devops/idpay-projects/06_pipeline_idpay-idpay-portal-welfare-backend-role-permission.tf
- azure-devops/idpay-projects/06_pipeline_idpay-notification-manager.tf
- azure-devops/idpay-projects/06_pipeline_idpay-onboarding-workflow.tf
- azure-devops/idpay-projects/06_pipeline_idpay-payment-instrument.tf
- azure-devops/idpay-projects/06_pipeline_idpay-reward-calculator.tf
- azure-devops/idpay-projects/06_pipeline_idpay-reward-user-id-splitter.tf
- azure-devops/idpay-projects/06_pipeline_idpay-timeline.tf
- azure-devops/idpay-projects/06_pipeline_idpay-transactions.tf
- azure-devops/idpay-projects/06_pipeline_idpay-wallet.tf
- azure-devops/idpay-projects/99_locals.tf
Add UAT configuration on pipeline and env. var.
Deploy on UAT
- [] No
---
> feat: IId 32 aggiunta service connection di uat

- azure-devops/rtd-projects/00_keyvault.tf
- azure-devops/rtd-projects/00_secrets_rtd.tf
- azure-devops/rtd-projects/03_service_connection_tls_certificate.tf
- azure-devops/rtd-projects/03_service_connections_aks.tf
- azure-devops/rtd-projects/06_pipeline_devops-java-springboot-color.tf
- azure-devops/rtd-projects/06_pipeline_rtd-cert-mounter.tf
- azure-devops/rtd-projects/10_tlscert-dev01-rtd-internal-dev-cstar-pagopa-it.tf
- azure-devops/rtd-projects/10_tlscert-prod01-rtd-internal-cstar-pagopa-it.tf
- azure-devops/rtd-projects/10_tlscert-uat01-rtd-internal-uat-cstar-pagopa-it.tf
- azure-devops/rtd-projects/99_variables.tf
- azure-devops/rtd-projects/README.md
- added rtd certificate for prod
- added devops color and aks cert mounter for prod
- minor fix
Allow the RTD on prod for aks
---
> feat: RTD certificate on PROD

- azure-devops/iac-projects/00_secrets_kv_tae.tf
- azure-devops/iac-projects/03_iac_tae.tf
- azure-devops/iac-projects/99_variables.tf
- azure-devops/iac-projects/README.md
- added iac pipelines for tae
Allow tae pipelines
---
> feat: Created tae-pipelines for iac

- azure-devops/rtd-projects/06_pipeline_devops-decrypter.tf
- azure-devops/rtd-projects/06_pipeline_devops-enrolled-payment-instrument.tf
- azure-devops/rtd-projects/06_pipeline_devops-file-register.tf
- azure-devops/rtd-projects/06_pipeline_devops-file-report.tf
- azure-devops/rtd-projects/06_pipeline_devops-ingestor.tf
- azure-devops/rtd-projects/06_pipeline_devops-pi-event-processor.tf
- azure-devops/rtd-projects/06_pipeline_devops-sender-auth.tf
This PR enables PROD pipelines to deploy to new k8s cluster.
---
> feat: Enable prod pipelines

- azure-devops/iac-projects/03_iac_core.tf
- azure-devops/iac-projects/03_iac_idpay.tf
- azure-devops/iac-projects/03_iac_tae.tf
Code review pipelines for iac, now use plan service connection for azure
---
> feat: IAC/Code review updated plan service connection

- azure-devops/iac-projects/03_iac_switcher.tf
- azure-devops/iac-projects/README.md
> feat: Increased switcher timeout

- azure-devops/iac-projects/03_iac_switcher.tf
> chore: Increased switcher pipeline timeout

- azure-devops/iac-projects/03_iac_switcher.tf
> feat: Upgraded switcher

- azure-devops/core-projects/03_service_connection_tls_certificate.tf
- azure-devops/idpay-projects/03_service_connection_tls_certificate.tf
- azure-devops/idpay-projects/10_tlscert-dev01-idpay-internal-dev-cstar-pagopa-it.tf
- azure-devops/idpay-projects/10_tlscert-prod01-idpay-internal-cstar-pagopa-it.tf
- azure-devops/idpay-projects/10_tlscert-uat01-idpay-internal-uat-cstar-pagopa-it.tf
- azure-devops/rtd-projects/03_service_connection_tls_certificate.tf
- azure-devops/rtd-projects/10_tlscert-dev01-rtd-internal-dev-cstar-pagopa-it.tf
- azure-devops/rtd-projects/10_tlscert-prod01-rtd-internal-cstar-pagopa-it.tf
- azure-devops/rtd-projects/10_tlscert-uat01-rtd-internal-uat-cstar-pagopa-it.tf
- azure-devops/rtd-projects/99_variables.tf
- changed trigger day for tls cert pipelines from Monday to Thursay
- for rtd tls cert token renew
- updated module version for tls cert service connection
- Fix tls cert pipelines broken
---
> fix: RTD-2162 tls-cert-rtd renew token and change trigger day

- .utils/terraform_run_all.sh
- azure-devops/iac-projects/.terraform.lock.hcl
- azure-devops/idpay-projects/.terraform.lock.hcl
- azure-devops/idpay-projects/00_generic.tf
- azure-devops/idpay-projects/06_pipeline_idpay-admissibility-assessor.tf
- azure-devops/idpay-projects/06_pipeline_idpay-group.tf
- azure-devops/idpay-projects/06_pipeline_idpay-iban.tf
- azure-devops/idpay-projects/06_pipeline_idpay-idpay-portal-welfare-backend-config.tf
- azure-devops/idpay-projects/06_pipeline_idpay-idpay-portal-welfare-backend-initiative.tf
- azure-devops/idpay-projects/06_pipeline_idpay-idpay-portal-welfare-backend-role-permission.tf
- azure-devops/idpay-projects/06_pipeline_idpay-initiative-statistics.tf
- azure-devops/idpay-projects/06_pipeline_idpay-kafka-connect.tf
- azure-devops/idpay-projects/06_pipeline_idpay-merchant.tf
- azure-devops/idpay-projects/06_pipeline_idpay-mock.tf
- azure-devops/idpay-projects/06_pipeline_idpay-notification-email.tf
- azure-devops/idpay-projects/06_pipeline_idpay-notification-manager.tf
- azure-devops/idpay-projects/06_pipeline_idpay-onboarding-workflow.tf
- azure-devops/idpay-projects/06_pipeline_idpay-payment-instrument.tf
- azure-devops/idpay-projects/06_pipeline_idpay-payment.tf
- azure-devops/idpay-projects/06_pipeline_idpay-ranking.tf
- azure-devops/idpay-projects/06_pipeline_idpay-recovery-error-topic.tf
- azure-devops/idpay-projects/06_pipeline_idpay-reward-calculator.tf
- azure-devops/idpay-projects/06_pipeline_idpay-reward-notification.tf
- azure-devops/idpay-projects/06_pipeline_idpay-reward-user-id-splitter.tf
- azure-devops/idpay-projects/06_pipeline_idpay-timeline.tf
- azure-devops/idpay-projects/06_pipeline_idpay-transactions.tf
- azure-devops/idpay-projects/06_pipeline_idpay-wallet.tf
- azure-devops/idpay-projects/README.md
- azure-devops/rtd-projects/.terraform.lock.hcl
- azure-devops/rtd-projects/README.md
> feat: Idpay added authorization for aks and ACR

- .github/workflows/static_analisys.yml
- .github/workflows/static_analisys_pr.yml
Updated version to allow to use the 1.8.5 terraform version
---
> fix: Static Analisys github action

- azure-devops/mil-projects/.terraform.lock.hcl
- azure-devops/mil-projects/00_secrets_azdo.tf
- azure-devops/mil-projects/00_secrets_mil.tf
- azure-devops/mil-projects/03_service_connection_tls_certificate.tf
- azure-devops/mil-projects/10_tlscert-mil-internal-cstar-pagopa-it.tf
- azure-devops/mil-projects/10_tlscert-mil-internal-dev-cstar-pagopa-it.tf
- azure-devops/mil-projects/10_tlscert-mil-internal-uat-cstar-pagopa-it.tf
- azure-devops/mil-projects/99_main.tf
- azure-devops/mil-projects/README.md
> feat: MIL UAT Tls certificate

- azure-devops/mil-projects/.terraform.lock.hcl
- azure-devops/mil-projects/00_secrets_mil.tf
- azure-devops/mil-projects/00_service_endpoint_docker.tf
- azure-devops/mil-projects/03_service_connections_aks.tf
- azure-devops/mil-projects/06_pipeline_mil_deploy.tf
- azure-devops/mil-projects/99_locals.tf
> feat: added mil deploy pipeline

- azure-devops/mil-projects/06_pipeline_mil_deploy.tf
> feat: Fixed branch reference

- azure-devops/.env/terraform.tfvars
- azure-devops/core-projects/.terraform.lock.hcl
- azure-devops/core-projects/03_service_connections_docker_federated.tf
- azure-devops/core-projects/99_main.tf
- azure-devops/core-projects/99_variables.tf
- azure-devops/core-projects/README.md
- azure-devops/mil-projects/00_secrets_mil.tf
- azure-devops/mil-projects/00_service_endpoint_docker.tf
- azure-devops/mil-projects/03_service_connections_aks.tf
- azure-devops/mil-projects/06_pipeline_mil_deploy.tf
- azure-devops/mil-projects/99_locals.tf
- azure-devops/mil-projects/README.md
Use workload identity service connection for ACR allow us to avoid to recreate every time
---
> feat: Added Azure container registry service connection with workload identity

- azure-devops/iac-projects/.terraform.lock.hcl
- azure-devops/iac-projects/00_secrets_kv_azdo.tf
- azure-devops/iac-projects/00_secrets_kv_idpay.tf
- azure-devops/iac-projects/00_secrets_kv_rtd.tf
- azure-devops/iac-projects/00_secrets_kv_tae.tf
- azure-devops/iac-projects/02_service_connections_azure_plan.tf
- azure-devops/iac-projects/03_iac_core.tf
- azure-devops/iac-projects/03_iac_idpay.tf
- azure-devops/iac-projects/03_iac_rtd.tf
- azure-devops/iac-projects/03_iac_switcher.tf
- azure-devops/iac-projects/03_iac_tae.tf
- azure-devops/iac-projects/04_backups.tf
- azure-devops/iac-projects/99_main.tf
- azure-devops/iac-projects/README.md
- upgrated modules and providers to use last version
Updated IaC permession to allow iac user to read eventhub namespace
---
> feat: Updated roles for iac pipelines

- azure-devops/iacv2-projects/99_locals.tf
**Description:**
This pull request adds the core-secrets project configuration to `locals.tf`. It includes the setup of associated environments, pipeline settings, and repository details. These updates ensure that code review and deployment processes are aligned with the organization's existing standards. 
- Configured the core-secrets project in `locals.tf`
- Added pipeline-related configurations
- Included repository and environment details
The update is required to introduce the core-secrets project into the infrastructure, ensuring standardized deployment and code review processes.
No
> feat: [PAYMCLOUD-302] Add core-secrets project configuration to locals.tf

- azure-devops/iacv2-projects/99_locals.tf
> feat: Enable iac mil prod

- azure-devops/mil-projects/08_pipeline_test_platform.tf
- azure-devops/mil-projects/README.md
> feat(mil): add emd test platform

- azure-devops/.env/core-itn_state.tfvars
- azure-devops/core-itn-projects/.terraform.lock.hcl
- azure-devops/core-itn-projects/00_data.tf
- azure-devops/core-itn-projects/00_secrets_domain.tf
- azure-devops/core-itn-projects/00_service_connection.tf
- azure-devops/core-itn-projects/03_service_connections_tls_certificate.tf
- azure-devops/core-itn-projects/10_tls_certs_itn_core.tf
- azure-devops/core-itn-projects/99_locals.tf
- azure-devops/core-itn-projects/99_main.tf
- azure-devops/core-itn-projects/99_variables.tf
- azure-devops/core-itn-projects/README.md
- azure-devops/core-projects/20_tls_certs_legacy.tf
- azure-devops/core-projects/99_locals.tf
- azure-devops/core-projects/99_main.tf
- added core-itn project
- added service connection tls
- added argocd.internal certificate pipelines
Allow to have argocd certificates
---
> feat: Created core-itn project and argocd.internal certificate

- azure-devops/iacv2-projects/99_locals.tf
> feat: Removed packer iac pipelines from WEU

- azure-devops/idpay-itn-projects/.terraform.lock.hcl
- azure-devops/idpay-itn-projects/10_tls_certs.tf
- azure-devops/idpay-itn-projects/99_main.tf
- azure-devops/idpay-itn-projects/README.md
> feat: add tls certificate registrobeni.x.cstar.pagopa.it

- azure-devops/idpay-itn-projects/10_tls_certs.tf
- Update dns recordname registrobeni to registrodeibeni
---
> fix: [RDB-10] update dns recordname

- azure-devops/rtd-projects/06_pipeline_devops-alternative-gateway.tf
- azure-devops/rtd-projects/06_pipeline_devops-decrypter.tf
- azure-devops/rtd-projects/06_pipeline_devops-enrolled-payment-instrument.tf
- azure-devops/rtd-projects/06_pipeline_devops-exporter.tf
- azure-devops/rtd-projects/06_pipeline_devops-file-register.tf
- azure-devops/rtd-projects/06_pipeline_devops-file-report.tf
- azure-devops/rtd-projects/06_pipeline_devops-idpay-lolab-payment.tf
- azure-devops/rtd-projects/06_pipeline_devops-ingestor.tf
- azure-devops/rtd-projects/06_pipeline_devops-io-mock.tf
- azure-devops/rtd-projects/06_pipeline_devops-payment-instrument.tf
- azure-devops/rtd-projects/06_pipeline_devops-pi-event-processor.tf
> fix(tae): added workload Identity client ID to pipelines

- azure-devops/srtp-itn-projects/06_pipeline_srtp_front_end_deploy.tf
- azure-devops/srtp-itn-projects/10_tls_certs.tf
- azure-devops/srtp-itn-projects/99_locals.tf
- azure-devops/srtp-itn-projects/README.md
> feat: SRTP fe

- azure-devops/idpay-itn-projects/00_secrets_domain.tf
- azure-devops/idpay-itn-projects/20_pipeline_argocd_aks_deploy.tf
> feat: add argocd credentials

- azure-devops/idpay-itn-projects/30_pipeline_idpay_asset_register_frontend.tf
- azure-devops/idpay-itn-projects/30_pipeline_idpay_bonus_portal_merchants_operator_frontend.tf
- azure-devops/idpay-itn-projects/30_pipeline_idpay_bonus_portal_users_frontend.tf
- azure-devops/idpay-itn-projects/30_pipeline_idpay_welfare_portal_frontend.tf
- azure-devops/idpay-itn-projects/30_pipeline_idpay_welfare_portal_merchants_frontend.tf
- azure-devops/idpay-itn-projects/30_pipeline_welfare_portal_merchants_frontend.tf
- azure-devops/idpay-itn-projects/99_locals.tf
> feat: IDP-2796 update pipelines frontend reference for the cdn

- azure-devops/idpay-itn-projects/99_locals.tf
> fix: IDP-2797 welfare-italy.dev changed into welfare.dev

- azure-devops/idpay-itn-projects/30_pipeline_idpay_bonus_portal_users_frontend.tf
- azure-devops/idpay-itn-projects/99_locals.tf
- Add keycloak  variables for user portal
---
> fix: update keycloak portal user variables

- azure-devops/idpay-itn-projects/30_pipeline_idpay_bonus_portal_merchants_operator_frontend.tf
- azure-devops/idpay-itn-projects/99_locals.tf
> fix: Azure front door purge variables

- azure-devops/idpay-itn-projects/30_pipeline_idpay_bonus_portal_merchants_operator_frontend.tf
- azure-devops/idpay-itn-projects/99_locals.tf
> fix: add variable to deploy pipelines

- azure-devops/idpay-itn-projects/99_locals.tf
- Update endpoint and profile for asset register
---
> fix: update cdn profile and endpoint for asset register

- azure-devops/iacv2-projects/00_generic.tf
- azure-devops/iacv2-projects/03_service_connections_azure_deploy.tf
> fix: Approval serv conn@prod

- azure-devops/idpay-itn-projects/08_pipeline_test_performance.tf
> fix: rename eie pipeline with pari

- azure-devops/idpay-itn-projects/99_locals.tf
Fix uri for idpay user portal
Fix uri for idpay user portal
---
> fix: url_api_portal_users

- azure-devops/core-itn-projects/10_tls_certificate_itn_core.tf
> feat: Added influxdb certificates

- azure-devops/core-projects/30_tls_certs_weu.tf
this endpoint will be used by the resource inside the domain platform
---
> feat: RTD-2658 created platform certificate for app gw

- azure-devops/idpay-itn-projects/30_pipeline_idpay_bonus_portal_merchants_operator_frontend.tf
- azure-devops/idpay-itn-projects/99_locals.tf
> feat: Add default initiative for dev and uat
